export const testIds = {
  header: 'site-header',
  desktopNav: 'desktop-navigation',
  mobileNav: 'mobile-navigation',
  mobileMenuTrigger: 'mobile-menu-trigger',
  hero: 'home-hero',
  heroPrimaryCta: 'hero-primary-cta',
  heroProductsCta: 'hero-products-cta',
  pillars: 'company-pillars-section',
  services: 'services-section',
  serviceCard: (slug: string) => `service-card-${slug}`,
  featuredWork: 'featured-work-section',
  projectCard: (slug: string) => `project-card-${slug}`,
  products: 'products-section',
  productCard: (slug: string) => `product-card-${slug}`,
  productUpdates: 'product-updates-section',
  productUpdate: (slug: string) => `product-update-${slug}`,
  latestUpdates: 'latest-updates-section',
  leadership: 'leadership-section',
  leadershipProfile: (slug: string) => `leadership-profile-${slug}`,
  team: 'team-section',
  teamMember: (slug: string) => `team-member-${slug}`,
  interns: 'interns-section',
  internProfile: (slug: string) => `intern-profile-${slug}`,
  testimonials: 'testimonials-section',
  testimonial: (id: string) => `testimonial-${id}`,
  about: 'about-section',
  contactCta: 'contact-cta-section',
  footer: 'site-footer',
} as const
